board:
  name: "Caravelle BLE"
  url: "https://github.com/zmkfirmware/zmk"
  vendor: "ZMK Contributors"
  soc: "nrf52832"

build:
  identifier: "caravelle"
  arch: "arm"
  type: "keyboard"
  outputs:
    - usb
    - ble

