# ZMK Build Matrix
# zmkfirmware/zmk の build-user-config.yml が読み込むビルド定義ファイル

include:
  # 左手側のビルド設定
  - board: nrf52dk
    shield: caravelle_left
    artifact-name: caravelle_ble_left

  # 右手側のビルド設定
  - board: nrf52dk
    shield: caravelle_right
    artifact-name: caravelle_ble_right
