shield:
  name: caravelle
  type: keyboard
  output: ble
  features:
    - keys
  
  # シールドのベンダー/デザイナー情報
  vendor: satt99
  
  # このシールドがサポートするボード
  compatible:
    - caravelle

  # 左右分割用の追加シールド定義（サブシールド）
  shields:
    - name: caravelle_left
      type: left
    - name: caravelle_right
      type: right
